### ISSUE TITLE
Horizontal prop not passed to FlatList

### ISSUE THREAD

**Issue by heysailor** [nandorojo/react-native-anchors#1]
Thank you for a very handy library. Minor bug - the `horizontal` prop of the exported FlatList is not passed to the underlying React Native FlatList.

**Comment by nandorojo** [comment]
Oh good catch, mind sending a PR?

**Comment by heysailor** [comment]
☝️☝️ just missed each other!

**Comment by nandorojo** [comment]
All set, will publish soon
